### ISSUE TITLE
Please explain why and how this works

### ISSUE THREAD

**Issue by leonklingele** [BalintCsala/Kaktoos#4]
Hey there,

can you please give a short summary on why and how this program works? I don't know anything at all about the internals of Minecraft but am very interested in learning more on it.

To better understand my questions, here is how I would probably have implemented this (on CPU) if I were given the task:

- Spawn multiple threads, each doing the following
  1. Increment some thread-local seed
  2. Generate a new Minecraft world using that seed (involves an external call to the Minecraft Java app)
  3. Access the "raw block-data" of some random parts of the generated world
  4. Extract all cacti by ID
  5. Find cacti that consist of multiple cacti blocks on top of each other
  6. Store seed of world with tallest cactus

Obviously, this implementation would be super slow.

- The search runs entirely on GPU without any external dependencies (such as to Minecraft itself). Does this mean all relevant parts of the world/cacti generation have been reimplemented in those few lines? Has this been reverse-engineered or are the algorithms documented publicly?
- Where does it find the height of a cactus? Where does it find cacti at all? Does it check for some kind of ID? Some extraction seems to be done in [`extract`](https://github.com/minecrafthome/kaktoos/blob/a9f5df86a67f92662d5a1475edfb16fb5c5b0703/kaktoos.cu#L42-L44). What's going on with `heightMap`, what does it store?

I'd love to see a little code walkthrough of the first 140 lines! :)

**Comment by BalintCsala** [comment]
It just simulates the cacti as if the ground level was at a set height at every coordinate inside a chunk. Yes, it reimplements the cactus code from minecraft based on reverse engineered code, it is not documented publicly. No world generation apart from that is used.

`extract` is just an optimization, it **extracts** the height from the **height**Map array (which as the name suggests, stores the height of the terrain including the cacti) at a certain location (e.g. at coords (3, 6)), this way we can work on 32 bit ints instead of 8 bits, which the GPU doesn't like as much

**Comment by leonklingele** [comment]
Thank you — that explains a lot!
